### ISSUE TITLE
drush_print_table() not available without drush

### ISSUE THREAD

**Issue by acouch** [NuCivic/dkan_starter#40]
## Description
I got: ``Fatal error: Call to undefined function drush_print_table() in  /assets/modules/data_config/data_config.module on line 257`` when disabling a module in the UI. 

## Steps to Reproduce
Disable a rules UI in the UI.

**Comment by drkloc** [comment]
@acouch https://github.com/NuCivic/dkan_starter/pull/32 that was already fixed there

**Comment by acouch** [comment]
Thanks.
